### ISSUE TITLE
 Is there a file missing issue？

### ISSUE THREAD

**Issue by xiaochenkeai** [AtticusXu/Modeling-Unknown-Stochastic-Dynamical-System-via-Autoencoder#1]
I noticed that there were missing datasets and missing definitions of some variables in the given file. I get an error when I try to run DEAE_train.py and the error is "No such file or directory: 'jsons/Ex1GeoBrownian.json'. Name 'model_dir' and 'data_type' is also not defined. I wonder if you have time to provide the complete code, I would appreciate it！

**Comment by AtticusXu** [comment]
Sorry, I've uploaded the json folder
